### ISSUE TITLE
Unable to start daemon

### ISSUE THREAD

**Issue by posix4e** [bakoushin/poh-validator-hcaptcha-api#1]
$ npm run docker-build
```
> poh-validator-hcaptcha-api@0.0.1 docker-build
> docker build -t bakoushin/poh-validator-hcaptcha .

Sending build context to Docker daemon  370.7kB
Step 1/6 : FROM node:16-alpine
 ---> b0cbdedc1b9d
Step 2/6 : ENV NPM_CONFIG_LOGLEVEL=warn
 ---> Using cache
 ---> d9291db87154
Step 3/6 : WORKDIR /usr/src/app
 ---> Using cache
 ---> 5b0020e02af7
Step 4/6 : COPY . .
 ---> Using cache
 ---> 3d9502ee38f4
Step 5/6 : RUN npm install --only=production
 ---> Using cache
 ---> c7f45f0d2f7c
Step 6/6 : CMD npm run docker
 ---> Using cache
 ---> 184e3a60d3a2
Successfully built 184e3a60d3a2
Successfully tagged bakoushin/poh-validator-hcaptcha:latest
```
$ docker run --rm bakoushin/poh-validator-hcaptcha

```
> poh-validator-hcaptcha-api@0.0.1 docker
> NODE_ENV=production node index.js

/usr/src/app/node_modules/@ethersproject/bytes/lib/index.js:9
    return !!(value.toHexString);
                    ^

TypeError: Cannot read properties of undefined (reading 'toHexString')
    at isHexable (/usr/src/app/node_modules/@ethersproject/bytes/lib/index.js:9:21)
    at hexlify (/usr/src/app/node_modules/@ethersproject/bytes/lib/index.js:175:9)
    at new SigningKey (/usr/src/app/node_modules/@ethersproject/signing-key/lib/index.js:20:82)
    at new Wallet (/usr/src/app/node_modules/@ethersproject/wallet/lib/index.js:123:36)
    at file:///usr/src/app/api.js:6:16
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)
```

**Comment by bakoushin** [comment]
It is required to provide some environment variables.
Example in the docs: https://github.com/bakoushin/poh-validator-hcaptcha-api#environment-variables

Although the error message is not quite informative, I will attempt to make it clearer.
